# Generated by Django 5.2.1 on 2026-09-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0206_historicopapbusca_login_pap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopapbusca',
            options={'ordering': ['-iniciado_em'], 'verbose_name': 'Busca histórico PAP', 'verbose_name_plural': 'Buscas histórico PAP'},
        ),
        migrations.AlterModelOptions(
            name='historicopappedido',
            options={'ordering': ['-capturado_em'], 'verbose_name': 'Pedido histórico PAP', 'verbose_name_plural': 'Pedidos histórico PAP'},
        ),
        migrations.RenameIndex(
            model_name='listaagendamentovendedorenviado',
            new_name='crm_lista_a_data_re_5feb37_idx',
            old_name='crm_lista_a_data_re_7c2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='nioreagendamentoitem',
            new_name='crm_nio_rea_execuca_756012_idx',
            old_name='crm_nio_re_exec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nioreagendamentoitem',
            new_name='crm_nio_rea_venda_i_085b19_idx',
            old_name='crm_nio_re_venda_fin_idx',
        ),
        migrations.AlterField(
            model_name='historicobuscafatura',
            name='tipo_busca',
            field=models.CharField(choices=[('AUTOMATICA', 'Busca Automática (Agendada)'), ('SAFRA', 'Busca por Safra'), ('INDIVIDUAL', 'Busca Individual'), ('RETRY', 'Retry de Erro'), ('MATCH_NOTURNO', 'Match noturno Nio (22h–7h)')], help_text='Tipo de execução', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicopapbusca',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicopappedido',
            name='tipo_venda',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('INTERESSE', 'Interesse'), ('PRE_VENDA', 'Pré-venda')], db_index=True, default='VENDA', max_length=20),
        ),
    ]
