# Generated by Django 5.2.1 on 2026-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0207_alter_historicopapbusca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='pedido_pap',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Pedido PAP'),
        ),
    ]
