# Generated by Django 5.2.1 on 2026-09-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0209_venda_valor_plano_pap_venda_vendedor_matricula_pap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-data_programada', '-hora_programada'], 'verbose_name': 'Comunicado (Futura Telecom Informa)', 'verbose_name_plural': 'Comunicados'},
        ),
        migrations.AlterModelOptions(
            name='recordapoia',
            options={'ordering': ['-data_upload'], 'verbose_name': 'Arquivo Futura Telecom Apoia', 'verbose_name_plural': 'Arquivos Futura Telecom Apoia'},
        ),
        migrations.AddField(
            model_name='operadora',
            name='usa_pap_nio',
            field=models.BooleanField(default=False, help_text='Marque somente para a operadora Nio. O portal PAP não atende Vero, Velox nem demais operadoras; vendas sem este flag não entram na automação de status.', verbose_name='Usa PAP Nio'),
        ),
        migrations.AddField(
            model_name='plano',
            name='ignorar_preco_gdp',
            field=models.BooleanField(default=False, help_text='Marque em planos fora da tabela GDP (ex.: exclusivos CNPJ). O valor mensal do cadastro passa a valer, em vez do preço por município.', verbose_name='Preço fixo (não usar GDP)'),
        ),
        migrations.AddField(
            model_name='whatsappintegracaoconfig',
            name='envios_cliente_ativos',
            field=models.BooleanField(default=False, help_text='Só ligar quando o número oficial do plano (Meta Cloud API / WhatsAtende B) estiver configurado. O WhatsApp do time comercial nunca envia a clientes.', verbose_name='Envios a clientes ativos'),
        ),
        migrations.AddField(
            model_name='whatsappintegracaoconfig',
            name='numero_cliente_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Número oficial Meta / clientes (exibição)'),
        ),
        migrations.AddField(
            model_name='whatsappintegracaoconfig',
            name='numero_equipe_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Número do time comercial (exibição)'),
        ),
    ]
