# Generated by Django 5.2.1 on 2025-08-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfil',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
