# Generated by Django 5.2.4 on 2025-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_table_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
